M48
; DRILL file {KiCad 9.0.1} date 2026-01-12T22:58:22+0100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-01-12T22:58:22+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.700
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.300
%
G90
G05
T1
X97.0Y-61.01
X97.0Y-110.01
X155.0Y-61.01
X155.0Y-110.01
T2
X170.891Y-97.586
X170.891Y-109.016
M30
